import Head from 'next/head'
import Image from 'next/image'
import Email from '../components/Email'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Social from '../components/Social'
import styles from '../styles/Home.module.css'

export default function Home() {
  const summary = [
    {
      "id": 1,
      "number": 4,
      "name": "Frontend Projects"
    },
    {
      "id": 2,
      "number": 5,
      "name": "Backend Projects"
    },
    {
      "id": 3,
      "number": 3000,
      "name": "Commits This Year"
    }
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <section id='introduction' className='lg:mt-28 md:mt-28 mt-24 mb-28'>
          <div className="hero-content flex-col lg:flex-row-reverse" >
            <div>
              <p className='mb-2 text-[18px] text-[#64ffda]'>Hi, my name is</p>
              <h1 className="lg:text-[66px] md:text-[46px] text-[36px] font-bold text-[#ccd6f6]">Montasim -Al- Mamun.</h1>
              <h5 className='lg:text-[66px] md:text-[46px] text-[36px] font-bold text-[#8892b0]'>I build things for the web.</h5>
              <p className="mt-4 py-2 lg:w-7/12 text-[18px] text-[#8892b0]" > I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products using MERN Stack.</p >
              <a className="btn rounded-xs border-primary text-primary px-10 capitalize text-md mt-14 hover:bg-primary hover:opacity-70 hover:text-black" href='https://drive.google.com/file/d/1sR4CxyIYw1uIesJHWaERKDGOBwfOVUcH/view?usp=sharing' target='_blank' rel="noreferrer" > Download My Resume</a >
            </div >
          </div >
        </section >

        <section className='text-white mb-32'>
          <div className='max-w-screen-xl px-4 mx-auto sm:px-6 lg:px-8'>
            <ul
              className='mt-8 border-2 border-white border-opacity-25 divide-y-2 divide-white sm:grid sm:divide-y-0 sm:divide-x-2 sm:border-l-0 sm:border-r-0 divide-opacity-25 sm:grid-cols-3 text-center'
            >
              {
                summary.map(s =>
                  <li key={s.id} className='p-8'>
                    <p className='text-3xl font-extrabold text-primary'>{s.number}+</p>
                    <p className='mt-1 text-xl font-medium'>{s.name}</p>
                  </li>)
              }
            </ul>
          </div>
        </section>
      </main>

      <Footer />
      <Social />
      <Email />
    </div>
  )
}
