import Head from 'next/head'
import Image from 'next/image'
import { BiRightArrow } from 'react-icons/bi';
import professionalPhoto from '../assets/images/SHUVO Transparent BG.png'
import Email from '../components/Email'
import Footer from '../components/Footer'
import MobileSocial from '../components/MobileSocial';
import Navbar from '../components/Navbar'
import Social from '../components/Social'

export default function Home() {
  const summary = [
    {
      "id": 1,
      "number": 4,
      "name": "Frontend Projects"
    },
    {
      "id": 2,
      "number": 5,
      "name": "Backend Projects"
    },
    {
      "id": 3,
      "number": 3000,
      "name": "Commits This Year"
    }
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <section id='introduction' className='lg:mt-28 md:mt-28 mt-24 mb-28'>
          <div className="hero-content flex-col lg:flex-row-reverse" >
            <div>
              <p className='mb-2 text-[18px] text-[#64ffda]'>Hi, my name is</p>
              <h1 className="lg:text-[66px] md:text-[46px] text-[36px] font-bold text-[#ccd6f6]">Montasim -Al- Mamun.</h1>
              <h5 className='lg:text-[66px] md:text-[46px] text-[36px] font-bold text-[#8892b0]'>I build things for the web.</h5>
              <p className="mt-4 py-2 lg:w-7/12 text-[18px] text-[#8892b0]" > I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products using MERN Stack.</p >
              <a className="btn rounded-xs border-primary text-primary px-10 capitalize text-md mt-14 hover:bg-primary hover:opacity-70 hover:text-black" href='https://drive.google.com/file/d/1sR4CxyIYw1uIesJHWaERKDGOBwfOVUcH/view?usp=sharing' target='_blank' rel="noreferrer" > Download My Resume</a >
            </div >
          </div >
        </section >

        <section className='text-white mb-32'>
          <div className='max-w-screen-xl px-4 mx-auto sm:px-6 lg:px-8'>
            <ul
              className='mt-8 border-2 border-white border-opacity-25 divide-y-2 divide-white sm:grid sm:divide-y-0 sm:divide-x-2 sm:border-l-0 sm:border-r-0 divide-opacity-25 sm:grid-cols-3 text-center'
            >
              {
                summary.map(s =>
                  <li key={s.id} className='p-8'>
                    <p className='text-3xl font-extrabold text-primary'>{s.number}+</p>
                    <p className='mt-1 text-xl font-medium'>{s.name}</p>
                  </li>)
              }
            </ul>
          </div>
        </section>

        <section className='mb-24' id='about'>
          <div className='flex items-center gap-6'>
            <h3 className='lg:text-3xl md:text-3xl text-2xl text-accent font-bold'>About Me </h3>
            <hr className='bg-[#233554] lg:w-80 md:w-64 w-40 h-0.5'></hr>
          </div>

          <div className='flex flex-col md:flex-row lg:flex-row justify-between items-center md:items-start lg:items-start gap-y-8'>
            <div className='mt-12 text-justify lg:w-7/12 md:w-6/12 w-full'>
              <p>
                Hello! My name is Mohammad Montasim -Al- Mamun Shuvo and I enjoy creating things that live on the internet. My interest in web development started back in 2017 when I was doing a university project — turns out this project taught me a lot about HTML & CSS!
              </p>

              <p className='my-5'>
                Fast-forward to today, and I’ve had the privilege of working at an organization, as a Management Information System Officer (MIS). My main focus these days is building accessible, inclusive products and digital experiences using MERN Stack.
              </p>

              <p>
                So far, I&apos;ve built some exciting full stack project.
              </p>

              <p className='my-5'>
                Here are a few technologies I’ve been working with recently:
              </p>

              <div className='grid grid-cols-2 gap-2 w-96 mb-10 md:mb-0 lg:mb-0'>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' /> JavaScript (ES6+)</small>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' />React JS</small>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' />Node.js</small>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' />Express.js</small>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' />Tailwind CSS</small>
                <small className='flex items-center gap-x-3'><BiRightArrow className='text-primary' />BootStrap</small>
              </div>

              <MobileSocial />
            </div>

            <div className="w-64 md:w-64 lg:w-94 rounded-lg relative mt-0 md:mt-16 lg:mt-16">
              <span className="absolute inset-0 border-2 border-primary border-solid rounded-lg"></span>

              <div
                className="transition-transform transform bg-accent -translate-x-5 -translate-y-5 rounded-lg"
              >
                <Image src={professionalPhoto} alt="" />
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
      <Social />
      <Email />
    </div>
  )
}
